name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python: ['3.6', '3.7']
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        make setup-dev
        make venv
      env:
        SLUGIFY_USES_TEXT_UNIDECODE: yes
    - name: Check formatting with black
      run: make fmt-check
    - name: Lint with pylint
      run: make lint
    - name: Test with pytest
      run: make test
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.xml
